(async function(){
  const grid=document.getElementById('catalog-grid'), count=document.getElementById('count'), search=document.getElementById('search');
  const palette={frontend:'coral',backend:'blue',security:'mint',product:'coral',devops:'blue',data:'blue',design:'mint',hr:'coral',management:'mint',other:'blue'};
  let skills=[]; let filter='all';
  try{const response=await fetch('skills.json'); if(!response.ok) throw new Error('catalog unavailable'); skills=await response.json(); render();}
  catch(error){grid.innerHTML='<div class="empty-state">The catalog could not load. <a href="https://titanwings.github.io/colleague-skill-site/gallery/" target="_blank" rel="noreferrer">Open the source gallery ↗</a></div>';count.textContent='Catalog unavailable';}
  function esc(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function repoFor(skill){return skill.skill_repo||`https://titanwings.github.io/colleague-skill-site/gallery/${encodeURIComponent(skill.slug)}`}
  function render(){const query=(search.value||'').trim().toLowerCase();const visible=skills.filter(s=>{const tags=s.tags||[];const matchFilter=filter==='all'||tags.includes(filter);const hay=[s.name,s.description,s.description_en,s.author?.name,...tags].join(' ').toLowerCase();return matchFilter&&(!query||hay.includes(query))});count.textContent=`${visible.length} of ${skills.length} profiles`;grid.innerHTML=visible.length?visible.map((s,i)=>{const tag=(s.tags||['other'])[0], tone=palette[tag]||'blue';const tags=(s.tags||[]).slice(0,3).map(t=>`<span class="catalog-tag">${esc(t)}</span>`).join('');return `<a class="catalog-card" href="${esc(repoFor(s))}" target="_blank" rel="noreferrer"><div class="catalog-top"><span class="catalog-badge ${tone}-bg">${esc(tag).toUpperCase()}</span><span class="catalog-stars">${s.type==='meta-skill'?'META':'SKILL'}</span></div><h3>${esc(s.name)}</h3><p>${esc(s.description_en||s.description)}</p><div class="catalog-tags">${tags}</div><div class="catalog-by"><span class="mini-avatar ${tone}">${esc((s.author?.name||'C').charAt(0).toUpperCase())}</span><span>by ${esc(s.author?.name||'Community')} · ${esc(s.created_at||'community')}</span><span class="arrow">↗</span></div></a>`}).join(''):'<div class="empty-state">No profiles match this search.</div>'}
  document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');filter=button.dataset.filter;render()}));search.addEventListener('input',render);
})();
